### ISSUE TITLE
Provide default config when used as library

### ISSUE THREAD

**Issue by mikey179** [tueftler/doget#5]
Currently no default config is available when DoGet is used as a library. Applications that do this need to provide their own `.doget.yml` so that DoGet knows how to translate USE repositories into a downloadable URL.

One possible solution could be the use of https://github.com/jteeuwen/go-bindata. That would also allow to ship a DoGet binary without the additional `.doget.yml`.

**Comment by thekid** [comment]
Here's an idea:

* `config.Default()` - returns the default config supporting GitHub and BitBucket
* `config.Empty()` - returns an empty configuration supporting no repositories

Then add `func (c *Configuration) Merge(sources ...string)` to replace the `From` function.
